name: 🔍 Security Scan with Snyk

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Install Snyk
      run: npm install -g snyk

    - name: Auth to Snyk
      run: snyk auth ${{ secrets.SNYK_TOKEN }}

    - name: Run Snyk scan
      run: snyk test --json > snyk-report.json

    - name: Upload report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: snyk-report
        path: snyk-report.json
